= Rapport d’avancement du groupe “5.2”

ifdef::env-gitlab,env-browser[:outfilesuffix: .adoc]
:doctype: book
:stem: latexmath
:source-highlighter: coderay
:toc-title: Table des matières
:toc: macro
:sectnums:
:imagesdir: images


// Partie non numérotée
:sectnums!:
== PACT groupe 5.2 : Télékip52

=== Membres du groupe

* BOHORQUEZ CARO Maria
* DARRE Victor
* KHAIR Mohamed
* MENDIHARAT Titouan
* ROUX Nelson
* WEBERT Nans

=== Tuteur

* LE FEUVRE Jean

=== Encadrant génie logiciel

* LINGUAGLOSSA Leonardo

=== Encadrante interface et design

* MORVAN Aliénor

== Résumé du sujet choisi en français (PAN1)

_N’en avez-vous pas marre de remplir incessamment les mêmes formulaires sur internet ? Et si on vous proposait une extension web qui les remplirait automatiquement ? Voilà notre concept : mettez vos informations personnelles (carte d’identité, justificatif de domicile….) dans une seule application puis laissez l’extension web remplir tous vos formulaires !_

Voici le but de notre application : remplir automatiquement les formulaires. Notre idée part d'un constat simple : de plus en plus de démarches doivent être réalisées en ligne. Afin de les faciliter, nous avons pour projet de créer un outils qui englobe toutes vos informations sur un fichier (chiffré). Il sera ensuite utilisé pour remplir automatiquement les formulaires via une extension web !

== English Summary (PAN1)

_Aren't you tired to fill out the same forms over and over again on the internet? What if we offered you a web extension that would fill them in automatically? This is our project: place your personal information (identity card, proof of address, etc.) in a single application then let the web extension fill in all your forms!_

This is the purpose of our application: automatically fill out forms. Our idea starts from a statement : more and more procedures must be carried out online. In order to help with these steps, we plan on creating a tool which encompasses all your information in one (encrypted) file. It will then be used to automatically fill in the forms through a web extension!


// en PDF on ne peut pas controler la position de la toc
// Macros non supportées
ifndef::backend-pdf[]
== Table des matières
:toc-title:
toc::[]
endif::[]

// On numérote le reste des sections
:sectnums:

== Étude d’antériorité et justification de la proposition (PAN1)

include::pan1/proposition/proposition.adoc[Description de la proposition]

include::pan1/proposition/etat-de-l-art.adoc[Description de l’état de l’art]

== Scénarios d’usage (PAN1)

include::pan1/scenario/scenario.adoc[Scénarios d’usage]

<<<

== Architecture du projet (PAN1)

include::pan1/architecture/schema.adoc[Schéma d’architecture]

include::pan1/architecture/interfaces.adoc[Description des interfaces]

include::pan1/architecture/sequence.adoc[Diagramme de séquence]

include::pan1/architecture/ihm.adoc[Interface utilisateur graphique]

<<<

== Organisation du projet (PAN1)

include::pan1/organisation/planification.adoc[Diagramme de planification temporel des tâches]

include::pan1/organisation/plan-tests.adoc[Plans de test (PAN2+)]

<<<

== PAN2

Lorsque le PAN1 s'est terminé, le PAN2 a logiquement commencé. Durant ce PAN2, nous avons pu commencer à travailler sur auto-form.
Chaque personne était en binômes pour suivre, 2 ou 3 modules (la liste des modules est disponible aux chapitres du PAN1).

include::pan2/module_design/objectifs.adoc[Module Design]

<<<
 
include::pan2/module_application/module_applications.adoc[Module Application]

<<<

include::pan2/module_tests/module_tests.adoc[Module Tests & Intégration]

<<<

[bibliography]
== Bibliographie

include::References.adoc[Bibliographie]

<<<
////

== Annexes

include::annexes/modifications.adoc[Modifications (PAN2+)]

include::annexes/avancement.adoc[Avancement des modules]

include::annexes/moduleX.adoc[Avancement module X]

include::annexes/moduleY.adoc[Avancement module Y]

////