=== Description de l’état de l’art
ifdef::env-gitlab,env-browser[:outfilesuffix: .adoc]

// *_Note : 1 page max._*

// Décrivez, en les citant via la bibliographie, les approches/produits
// ressemblant à votre projet et les différences éventuelles. Illustrez
// avec des images si besoin. Utilisez des renvois vers votre
// bibliographie : « comme démontré dans [2], … »

==== Complétion auto native

Il existe déjà des auto complétions par les navigateurs :

* <<ChromeNative>>
* <<FirefoxNative>>
* <<EdgeNative>>

En comparaison à ceux-ci, ce qui nous différentie, est le fait de remplir les cases où des documents sont demandés. Ces autto complétions par les navigateurs sont capables de remplir les cases "nom de famille", "prénom", "mail", "adresse" et autres mais leur portée reste assez restreinte.

==== Extensions déjà existantes

* Roboform: Garde, gère et auto rempli les identifiants et les mots de passe. Bien qu'il ne remplisse pas des documents, il utilise un système similaire au notre pour remplir les cases. 

* Formfiller et DocFly: permettent de modifier les PDF. C'est l'utilisateur qui les remplit, l'application permet uniquement de "défaire" le caractère immodifiable du PDF.

 


// ==== Exemples de citations

// Les références bibliographiques sont regroupées dans le fichier `References.adoc`
// à la racine du répertoire `rapport`.
// On peut y faire référence dans toutes les sous parties du document.

// On peut citer comme exemple l'article de Claude E. Shannon sur la
// théorie de la communication <<RefShannon>>
// ou, bien évidement, la vitrine des projets PACT <<VitrinePACT>>.

// Voir <<TOTO,la référence>> très intéressante elle aussi.
