module.exports = {
    "NO_TOKEN": "NO_TOKEN",
    "NO_PASSWORD": "NO_PASSWORD",
    "Forbidden": "Forbidden",
    "BAD_HEADER": "BAD_HEADER",
    "DB_ALREADY_OPEN": "DB_ALREADY_OPEN",
    "EMPTY_BODY": "EMPTY_BODY",
    "DB_NOT_OPEN": "DB_NOT_OPEN",
    "INCORRECT_PASSWORD": "INCORRECT_PASSWORD"
}