icons:
	inkscape -w 16 -h 16 public/img/auto_form.svg -o assets/app-icon/png/16.png
	inkscape -w 24 -h 24 public/img/auto_form.svg -o assets/app-icon/png/24.png
	inkscape -w 32 -h 32 public/img/auto_form.svg -o assets/app-icon/png/32.png
	inkscape -w 48 -h 48 public/img/auto_form.svg -o assets/app-icon/png/48.png
	inkscape -w 64 -h 64 public/img/auto_form.svg -o assets/app-icon/png/64.png
	inkscape -w 128 -h 128 public/img/auto_form.svg -o assets/app-icon/png/128.png
	inkscape -w 256 -h 256 public/img/auto_form.svg -o assets/app-icon/png/256.png
	inkscape -w 512 -h 512 public/img/auto_form.svg -o assets/app-icon/png/512.png
	inkscape -w 1024 -h 1024 public/img/auto_form.svg -o assets/app-icon/png/1024.png
	convert -density 256x256 -background transparent public/img/auto_form.svg -define icon:auto-resize -colors 256 assets/app-icon/win/app.ico